In [1]:
import numpy as np

In [16]:
recommended_list = [143, 156, 1134, 991, 27, 1543, 3345, 533, 11, 43] #id товаров
bought_list = [521, 32, 143, 991]

In [4]:
def hit_rate(recommended_list, bought_list):
    
    bought_list = np.array(bought_list)
    recommended_list = np.array(recommended_list)
    
    flags = np.isin(bought_list, recommended_list)
    
    hit_rate = (flags.sum() > 0) * 1
    
    return hit_rate




In [5]:
print(hit_rate(recommended_list, bought_list))

1


In [12]:
recommended_list = np.array(recommended_list)
recommended_list_k = recommended_list[:5]
print(recommended_list_k)

[ 143  156 1134  991   27]


### 1. hit_rate_at_k 
Hit rate@k = (был ли хотя бы 1 релевантный товар среди топ-k рекомендованных)

In [17]:

def hit_rate_at_k(recommended_list, bought_list, k=5):
    
    # your_code
    bought_list = np.array(bought_list)
    recommended_list = np.array(recommended_list)
    recommended_list_k = recommended_list[:k]
    
    flags = np.isin(bought_list, recommended_list_k)
    
    hit_rate = (flags.sum() > 0) * 1
    
    return hit_rate

    
    return hit_rate

In [18]:
hit_rate_at_k(recommended_list, bought_list, k=3)

1

### 2. money_precision_at_k
Case 2
prices_resommended = [400, 60, 40, 40 , 90]
flags = [0, 1, 0, 0 , 1]

𝑝𝑟𝑒𝑐𝑖𝑠𝑜𝑛@5=0+1+0+0+11+1+1+1+1=40%

𝑚𝑜𝑛𝑒𝑦𝑝𝑟𝑒𝑐𝑖𝑠𝑖𝑜𝑛@5=0∗400+1∗60+...+1∗901∗400+1∗60+...+1∗90=15.8%

In [25]:
prices_resommended = [400, 60, 40, 40 , 90]

In [59]:
def money_precision_at_k(recommended_list, bought_list, prices_recommended, k=5):
        
    # your_code
    # Лучше считать через скалярное произведение, а не цикл
    bought_list = np.array(bought_list)
    recommended_list = np.array(recommended_list)
    prices_recommended = np.array(prices_recommended)
        
    recommended_list = recommended_list[:k]
    
    flags = np.isin(recommended_list, bought_list )
    flags = flags.astype(int)
       
    money_precision = (flags@prices_recommended) / (np.ones(len(flags)) @ prices_recommended)
    
    return money_precision

In [58]:
money_precis = money_precision_at_k(recommended_list, bought_list, prices_resommended, k=5)
print(money_precis)

[ 143  156 1134  991   27]
[521  32 143 991]
[1 0 0 1 0]
0.6984126984126984


### 3. recall_at_k

In [61]:
def recall_at_k(recommended_list, bought_list, k=5):
    
    # your_code
    bought_list = np.array(bought_list)
    recommended_list = np.array(recommended_list)
    
    recommended_list = recommended_list[: k]
    
    flags = np.isin(bought_list, recommended_list)
    
    recall = flags.sum() / len(bought_list)
    
    
    return recall


In [62]:
print(recall_at_k(recommended_list, bought_list, k=5))

0.5


### 4.money_recall_at_k
Money Recall@k = (revenue of recommended items @k that are relevant) / (revenue of relevant items)

In [66]:
prices_bought = [90, 60 , 40 , 40]


In [68]:
def money_recall_at_k(recommended_list, bought_list, prices_recommended, prices_bought, k=5):
    
    # your_code
    bought_list = np.array(bought_list)
    recommended_list = np.array(recommended_list)
    
    recommended_list = recommended_list[: k]
    
    flags = np.isin(recommended_list, bought_list )
    flags = flags.astype(int)
    print(flags)
    
    money_recall = (flags @ prices_recommended)/(np.ones(len(prices_bought))@prices_bought)
    
    return money_recall

In [69]:
print(money_recall_at_k(recommended_list, bought_list, prices_resommended, prices_bought, k =5))

[1 0 0 1 0]
1.9130434782608696


### 5. MAP@k

MAP@k (Mean Average Precision@k)
Среднее AP@k по всем юзерам

    Показывает средневзвешенную точность рекомендаций

𝑀𝐴𝑃@𝑘=1|𝑈|∑𝑢𝐴𝑃𝑘

In [73]:
def precision_at_k(recommended_list, bought_list, k=5):
    
    bought_list = np.array(bought_list)
    recommended_list = np.array(recommended_list)
    
    bought_list = bought_list  # Тут нет [:k] !!
    recommended_list = recommended_list[:k]
    
    flags = np.isin(bought_list, recommended_list)
    
    precision = flags.sum() / len(recommended_list)
    
    
    return precision

In [74]:
def map_k(recommended_list, bought_list, k=5):
    
    # your_code
     
    bought_list = np.array(bought_list)
    recommended_list = np.array(recommended_list)
    
    flags = np.isin(recommended_list, bought_list)
    
    if sum(flags) == 0:
        return 0
    
    sum_ = 0
    for i in range(1, k+1):
        
        if flags[i] == True:
            p_k = precision_at_k(recommended_list, bought_list, k=i)
            sum_ += p_k
            
    ap_k = sum_ / sum(flags)
    
    result = ap_k / len(recommended_list)
    return result

In [75]:
print(map_k(recommended_list, bought_list,k =5))

0.016666666666666666


### MRR@k

Mean Reciprocal Rank

    Считаем для первых k рекоммендаций
    Найти ранк первого релевантного предсказания 𝑘𝑢

Посчитать reciprocal rank = 1𝑘𝑢

In [76]:
def reciprocal_rank(recommended_list, bought_list):
    # your_code
    bought_list = np.array(bought_list)
    recommended_list = np.array(recommended_list)
           
    flags = np.isin(bought_list, recommended_list)
    flags = flags.astype(int)
    rs = (np.asarray(r).nonzero()[0] for r in flags)
    result = np.mean([1. / (r[0] + 1) if r.size else 0. for r in rs]) 
    return result

In [77]:
print(reciprocal_rank(recommended_list, bought_list))

0.5


/snap/jupyter/6/lib/python3.7/site-packages/ipykernel_launcher.py:8: DeprecationWarning: Calling nonzero on 0d arrays is deprecated, as it behaves surprisingly. Use `atleast_1d(arr).nonzero()` if the old behavior was intended.
  
